baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft CMS Test'
primary: true
siteGroup: 3fe1924b-6e29-4478-8339-dab670d8080d # Craft CMS Test
sortOrder: 1
