columnSuffix: null
contentColumnType: string
fieldGroup: f50dc7f6-014b-4f6b-8f59-6d93e6167a1c # Home Page
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a background image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
