columnSuffix: null
contentColumnType: string
fieldGroup: 866e8573-b0a5-48e1-af43-5011ef7554c4 # Common
handle: photos
instructions: ''
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a photo'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:7552a7a2-31f3-4113-b996-07eb356a45bf' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
