defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  5bbb0374-ff90-401c-8e26-8d9766708f0d: # Craft CMS Test
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
