defaultPlacement: end
enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  5bbb0374-ff90-401c-8e26-8d9766708f0d: # Craft CMS Test
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry
    uriFormat: 'stories/{slug}'
type: channel
